### ISSUE TITLE
Migration stops due to undefined spinner in verbose mode

### ISSUE THREAD

**Issue by cuyahoga** [jhipster/generator-jhipster-migrate#15]
Migrating an application for the first time from 7.9.3 to 8.4.0, the blueprint stops when regenerating the source app. Run with `jhipster-migrate --verbose` and selected default values for all prompts;

```
ERROR! failed to regenerate source application using JHipster current
ERROR! An error occured while running jhipster-migrate:migrate#prepareMigrateBranch
ERROR! ERROR! Cannot read properties of undefined (reading 'fail')
TypeError: Cannot read properties of undefined (reading 'fail')
    at default.regenerate (file:///C:/apps/nvm/v20.12.2/node_modules/generator-jhipster-migrate/generators/migrate/generator.js:551:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async default.prepareMigrateBranch (file:///C:/apps/nvm/v20.12.2/node_modules/generator-jhipster-migrate/generators/migrate/generator.js:327:9)
    at async default.executeTask (file:///C:/apps/nvm/v20.12.2/node_modules/generator-jhipster-migrate/node_modules/yeoman-generator/dist/actions/lifecycle.js:244:13)
    at async runLoop.add.once (file:///C:/apps/nvm/v20.12.2/node_modules/generator-jhipster-migrate/node_modules/yeoman-environment/dist/environment-base.js:395:17)
```

Remedied with a quick check before usage of `installSpinner`, same as is done for other spinners. Awaiting commit...

**Comment by mshima** [comment]
@cuyahoga can you provide a PR?

**Comment by cuyahoga** [comment]
@mshima yep, have one ready to contribute

**Comment by siuburu** [comment]
@cuyahoga how did you fix this?
