### ISSUE TITLE
Jhipster-migration doesn't update pom.xml

### ISSUE THREAD

**Issue by siuburu** [jhipster/generator-jhipster-migrate#17]
I am trying to update a JHipster app from version 7.9.0 to 8.4.0. The update script runs without issues, but after execution, the pom.xml file still shows Java 11 and JHipster 7.9.0. Is this normal behavior and should I manually update it myself?

**Comment by mshima** [comment]
Check if you have a `.yo-resolve` file ignoring pom.xml.

**Comment by siuburu** [comment]
Not at all.
![image](https://github.com/jhipster/generator-jhipster-migrate/assets/19828671/ba0d61e5-95c9-4f60-b142-94ae1bf92f0e)

**Comment by mshima** [comment]
The entire pom.xml or just a few parts?

**Comment by siuburu** [comment]
The entire pom.xml, no changes at all.

When trying to update another app from 7.9.4 to 8.4.0 i have another error:

```
✖ An error occured while running jhipster:entity-server#writeServerFiles
ERROR! /home/victor/projects/ouvidoria-service/node_modules/generator-jhipster/generators/entity-server/templates/src/main/java/package/service/mapper/EntityMapper.java.ejs:103
    101| <%_ } _%>
    102| <%_ for (const {otherEntity, relatedField, collection} of otherEntitiesFields) { _%>
 >> 103| <%_ const mapperName = otherEntity.entityInstance + _.upperFirst(relatedField.propertyName); _%>
    104| 
    105|     @Named("<%= mapperName %>")
    106|     @BeanMapping(ignoreByDefault = true)

Cannot read properties of undefined (reading 'propertyName')
TypeError: /home/victor/projects/ouvidoria-service/node_modules/generator-jhipster/generators/entity-server/templates/src/main/java/package/service/mapper/EntityMapper.java.ejs:103
    101| <%_ } _%>
    102| <%_ for (const {otherEntity, relatedField, collection} of otherEntitiesFields) { _%>
 >> 103| <%_ const mapperName = otherEntity.entityInstance + _.upperFirst(relatedField.propertyName); _%>
    104| 
    105|     @Named("<%= mapperName %>")
    106|     @BeanMapping(ignoreByDefault = true)

Cannot read properties of undefined (reading 'propertyName')
    at module.exports.eval ("/home/victor/projects/ouvidoria-service/node_modules/generator-jhipster/generators/entity-server/templates/src/main/java/package/service/mapper/EntityMapper.java.ejs":185:82)
    at EntityMapper.java (/home/victor/projects/ouvidoria-service/node_modules/ejs/lib/ejs.js:703:17)
    at /home/victor/projects/ouvidoria-service/node_modules/ejs/lib/ejs.js:260:40
    at new Promise (<anonymous>)
    at tryHandleCache (/home/victor/projects/ouvidoria-service/node_modules/ejs/lib/ejs.js:258:14)
    at Object.exports.renderFile (/home/victor/projects/ouvidoria-service/node_modules/ejs/lib/ejs.js:491:10)
    at Object.renderContent (/home/victor/projects/ouvidoria-service/node_modules/generator-jhipster/generators/utils.js:350:23)
    at module.exports.template (/home/victor/projects/ouvidoria-service/node_modules/generator-jhipster/generators/generator-base-private.js:735:8)
    at /home/victor/projects/ouvidoria-service/node_modules/generator-jhipster/generators/generator-base.js:2369:47
    at Array.map (<anonymous>) {
  path: '/home/victor/projects/ouvidoria-service/node_modules/generator-jhipster/generators/entity-server/templates/src/main/java/package/service/mapper/EntityMapper.java.ejs'
}
ERROR! failed to regenerate source application using JHipster current
ERROR! An error occured while running jhipster-migrate:migrate#prepareMigrateBranch
ERROR! ERROR! Command failed with exit code 1: npx --no -- jhipster --force --skip-install --skip-git --ignore-errors --no-insight --skip-checks --with-entities --prefer-global
Error: Command failed with exit code 1: npx --no -- jhipster --force --skip-install --skip-git --ignore-errors --no-insight --skip-checks --with-entities --prefer-global
    at makeError (file:///home/victor/.nvm/versions/node/v20.12.2/lib/node_modules/generator-jhipster-migrate/node_modules/execa/lib/error.js:60:11)
    at handlePromise (file:///home/victor/.nvm/versions/node/v20.12.2/lib/node_modules/generator-jhipster-migrate/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async default.regenerate (file:///home/victor/.nvm/versions/node/v20.12.2/lib/node_modules/generator-jhipster-migrate/generators/migrate/generator.js:584:7)
    at async default.prepareMigrateBranch (file:///home/victor/.nvm/versions/node/v20.12.2/lib/node_modules/generator-jhipster-migrate/generators/migrate/generator.js:327:9)
    at async default.executeTask (file:///home/victor/.nvm/versions/node/v20.12.2/lib/node_modules/generator-jhipster-migrate/node_modules/yeoman-generator/dist/actions/lifecycle.js:244:13)
    at async runLoop.add.once (file:///home/victor/.nvm/versions/node/v20.12.2/lib/node_modules/generator-jhipster-migrate/node_modules/yeoman-environment/dist/environment-base.js:395:17) {
  shortMessage: 'Command failed with exit code 1: npx --no -- jhipster --force --skip-install --skip-git --ignore-errors --no-insight --skip-checks --with-entities --prefer-global',
  command: 'npx --no -- jhipster --force --skip-install --skip-git --ignore-errors --no-insight --skip-checks --with-entities --prefer-global',
  escapedCommand: 'npx --no -- jhipster --force --skip-install --skip-git --ignore-errors --no-insight --skip-checks --with-entities --prefer-global',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  cwd: '/home/victor/projects/ouvidoria-service',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Comment by mshima** [comment]
Post your `jhipster info` output.

**Comment by mshima** [comment]
JHipster v7.9.4 or v7.9.0?

**Comment by siuburu** [comment]
> JHipster v7.9.4 or v7.9.0?

Sorry 7.9.3 to 8.4.0

**Comment by siuburu** [comment]
> JHipster v7.9.4 or v7.9.0?

Sorry 7.9.0, the other project that I mention is running Jhipster 7.9.3

Here's the output of `jhipster info`  in the first project:
```
jhipster info                 

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
                            https://www.jhipster.tech
Welcome to JHipster v8.4.0

Welcome to the JHipster Information Sub-Generator


```
ouvidoria-ui@0.0.1-SNAPSHOT /home/victor/projects/ouvidoria-ui-2023
└── (empty)
```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "gateway",
    "authenticationType": "oauth2",
    "baseName": "ouvidoriaUi",
    "blueprints": [],
    "buildTool": "maven",
    "cacheProvider": "no",
    "clientFramework": "angularX",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1690995270073,
    "databaseType": "no",
    "devDatabaseType": "no",
    "devServerPort": 4200,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entities": [
      "Manifestacao",
      "Arquivo"
    ],
    "entitySuffix": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.9.0",
    "languages": [
      "pt-br",
      "en",
      "es"
    ],
    "messageBroker": false,
    "microfrontend": false,
    "microfrontends": [],
    "nativeLanguage": "pt-br",
    "otherModules": [],
    "packageName": "br.mp.mpro.ouvidoria",
    "pages": [],
    "prodDatabaseType": "no",
    "reactive": true,
    "searchEngine": false,
    "serverPort": "8080",
    "serverSideOptions": [],
    "serviceDiscoveryType": "eureka",
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "skipUserManagement": true,
    "testFrameworks": [
      "cucumber"
    ],
    "websocket": false,
    "withAdminUi": false
  }
}
</pre>
</details>


##### **Environment and Tools**

openjdk version "17.0.10" 2024-01-16
OpenJDK Runtime Environment Temurin-17.0.10+7 (build 17.0.10+7)
OpenJDK 64-Bit Server VM Temurin-17.0.10+7 (build 17.0.10+7, mixed mode, sharing)

git version 2.34.1

node: v20.12.2
npm: 10.8.0

Docker version 26.1.3, build b72abbb

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Manifestacao {
  veiculo VeiculoManifestacao
  tipo TipoManifestacao
  assunto String
  anonimo Boolean
  nome String
  nomeSocial String
  logradouro String
  numero String
  bairro String
  cidade String
  cep String
  telefoneFixo String
  telefoneCelular String
  email String
  sexo String
  nascimento String
  profissao String
  escolaridade String
  cpf String
  rg String
  orgaoEmissorRg String
  estadoEmissorRg String
  eleitoral Boolean
  resposta Boolean
  oQue String
  onde String
  quando String
  como String
  quem String
  testemunha String
  complemento String
  isOutrosOrgaos Boolean
  nomeOutrosOrgaos String
  numeroOutrosOrgaos String
  sigilo Boolean
  data ZonedDateTime
  status StatusManifestacao
}
entity Arquivo {
  contentId UUID
  titulo String
  contentLen Long
  mimeType String
  bucket String
  hash String
  dataCadastro ZonedDateTime
}
enum VeiculoManifestacao {
  PORTAL,
  PRESENCIAL,
  WHATSAPP,
  TELEFONE,
  FAX,
  EMAIL,
  APLICATIVO
}
enum TipoManifestacao {
  COMENTARIO,
  CRITICA,
  DENUNCIA,
  ELOGIO,
  INFORMACAO,
  RECLAMACAO,
  SUGESTAO
}
enum StatusManifestacao {
  NOVA,
  EM_ANALISE,
  ANALISADA,
  TRANSFORMADA_NF,
  FINALIZADA
}

relationship ManyToOne {
  Arquivo{manifestacao(uid)} to Manifestacao
}

dto Manifestacao, Arquivo with mapstruct
paginate Manifestacao with pagination
service Manifestacao, Arquivo with serviceImpl
microservice Manifestacao, Arquivo with OuvidoriaService
clientRootFolder Manifestacao, Arquivo with OuvidoriaService

</pre>
</details>


Congratulations, JHipster execution is complete!
If you find JHipster useful consider sponsoring the project https://www.jhipster.tech/sponsors/

Thanks for using JHipster!

```

**Comment by siuburu** [comment]
Got it solved. Setting specific jhipster versions when using `jhipster-migrate --verbose`
